codecov:
  branch: master       # the branch to show by default, inherited from your git repository settings
                       # ex. master, stable or release
                       # default: the default branch in git/mercurial
  ci:
    - !appveyor                # ignore CI builds by AppVeyor
coverage:
  precision: 2         # how many decimal places to display in the UI: 0 <= value <= 4
  round: nearest       # how coverage is rounded: down/up/nearest
  range: 50...90      # custom range of coverage colors from red -> yellow -> green

  status:
    project:                   # measuring the overall project coverage
      default:                 # context, you can create multiple ones with custom titles
        enabled: yes           # must be yes|true to enable this status
        target: auto           # specify the target coverage for each commit status
                               #   option: "auto" (must increase from parent commit or pull request base)
                               #   option: "X%" a static target percentage to hit
        branches: null         # -> see "branch patterns" below
        threshold: 2%          # allowed to drop X% and still result in a "success" commit status

    patch:                     # pull requests only: this commit status will measure the
                               # entire pull requests Coverage Diff. Checking if the lines
                               # adjusted are covered at least X%.
      default:
        enabled: yes             # must be yes|true to enable this status
        target: 80%              # specify the target "X%" coverage to hit
        branches: null           # -> see "branch patterns" below
        threshold: null          # allowed to drop X% and still result in a "success" commit status
        if_no_uploads: error     # will post commit status of "error" if no coverage reports we uploaded
                                 # options: success, error, failure
        if_not_found: success
        if_ci_failed: error

  ignore:          # files and folders that will be removed during processing
    - "vendor/*"

# comment: false  # to disable comments
comment:
  layout: "header, diff, changes, sunburst, suggestions, tree"
  branches: null           # -> see "branch patterns" below
  behavior: default        # option: "default" posts once then update, posts new if delete
                           # option: "once"    post once then updates, if deleted do not post new
                           # option: "new"     delete old, post new
                           # option: "spammy"  post new
