language: go
os:
  - linux
  - osx
go:
  - go1.8
go_import_path: github.com/go-siris/siris
install:
  - go get ./...
# install test dependencies
  - go get golang.org/x/tools/cmd/cover
  - go get -v github.com/axw/gocov
  - go install github.com/axw/gocov/gocov
script:
  - gocov test $(go list ./... | grep -v /vendor/) | gocov report
 # For now keep it commented.
 # - cd ./_examples
 # - go get ./...
  - go test -v -cover $(go list ./... | grep -v /vendor/)
